sources:
  - ImageRandomizerApp/Application # you can provide either single path or several paths using `-`
  - ImageRandomizerApp/Library
templates:
  - Common/Extras/Sourcery/Templates # as well as for templates
output:
  ImageRandomizerApp/Resources/Generated/Sourcery.generated.swift # note that there is no `-` here as only single output path is supported
